(() => {
  const reviews = [
    { name: "Valentina R.", comment: "Llegó muy bien empacado y tal como se veía en las fotos. Muy buena compra.", date: "Hace 2 semanas", rating: 5 },
    { name: "Juan P.", comment: "Buena calidad por el precio. La entrega fue rápida y el vendedor respondió mis dudas.", date: "Hace 1 mes", rating: 5 },
    { name: "Camila G.", comment: "Me gustó mucho. El producto cumple con la descripción y volvería a comprar.", date: "Hace 2 meses", rating: 4 },
    { name: "Mateo L.", comment: "Excelente atención y producto. Recomendado para quien esté buscando algo así.", date: "Hace 3 semanas", rating: 5 },
    { name: "Laura M.", comment: "Todo llegó en orden. Buen material y muy fácil de usar.", date: "Hace 5 semanas", rating: 4 },
  ];

  const entries = [
    {
      id: "laptop-lenovo-ideapad", name: "Portátil Lenovo IdeaPad 15”", category: "Computadores",
      price: 2299000, previousPrice: 2799000, rating: 4.8, reviewCount: 124, stock: 8, sold: 312, age: 1,
      image: "assets/products/tech-laptop.jpg", alternate: "assets/products/computer-workstation.jpg",
      description: "Portátil veloz y ligero para estudiar, trabajar y disfrutar contenido. Incluye procesador de última generación, almacenamiento SSD y una pantalla nítida de 15 pulgadas.",
      keywords: "laptop notebook computador portátil lenovo estudio oficina windows",
      features: ["Pantalla Full HD de 15,6 pulgadas", "SSD de 512 GB", "Memoria RAM de 16 GB", "Garantía de 1 año"],
      variants: { color: ["Gris grafito", "Azul noche"] }, featured: true, bestSeller: true, isNew: true,
    },
    {
      id: "audifonos-bluetooth-pro", name: "Audífonos Bluetooth Pro", category: "Tecnología",
      price: 189900, previousPrice: 249900, rating: 4.7, reviewCount: 98, stock: 24, sold: 487, age: 3,
      image: "assets/products/tech-headphones.jpg", alternate: "assets/products/games-headset.jpg",
      description: "Audífonos inalámbricos con sonido envolvente, micrófono integrado y batería para acompañarte todo el día. Incluyen estuche de carga y cable USB-C.",
      keywords: "audifonos cascos headset bluetooth musica sonido inalambrico",
      features: ["Hasta 32 horas de batería", "Cancelación de ruido", "Bluetooth 5.3", "Micrófono para llamadas"],
      variants: { color: ["Negro", "Blanco", "Azul"] }, featured: true, bestSeller: true,
    },
    {
      id: "iphone-14-128", name: "iPhone 14 · 128 GB", category: "Celulares",
      price: 2899000, previousPrice: 3399000, rating: 4.9, reviewCount: 213, stock: 5, sold: 629, age: 2,
      condition: "Como nuevo",
      image: "assets/products/phone-smartphone.jpg", alternate: "assets/products/phone-mobile.jpg",
      description: "iPhone 14 en excelente estado, liberado para cualquier operador. Incluye caja, cable original y garantía de 6 meses.",
      keywords: "iphone apple celular movil smartphone telefono ios camara",
      features: ["Pantalla Super Retina XDR de 6,1 pulgadas", "128 GB de almacenamiento", "Cámara avanzada de 12 MP", "Batería revisada"],
      variants: { color: ["Azul", "Negro", "Morado"] }, featured: true, bestSeller: true, isNew: true,
    },
    {
      id: "galaxy-a55-5g", name: "Samsung Galaxy A55 5G", category: "Celulares",
      price: 1599000, previousPrice: 1899000, rating: 4.6, reviewCount: 86, stock: 13, sold: 205, age: 8,
      image: "assets/products/phone-mobile.jpg", alternate: "assets/products/phone-smartphone.jpg",
      description: "Galaxy A55 con conectividad 5G, pantalla AMOLED y batería de larga duración. Un celular completo para todos los días.",
      keywords: "samsung galaxy android celular movil smartphone telefono 5g",
      features: ["Pantalla Super AMOLED de 6,6 pulgadas", "256 GB de almacenamiento", "Cámara principal de 50 MP", "Batería de 5.000 mAh"],
      variants: { color: ["Azul hielo", "Lila", "Negro"] }, bestSeller: true,
    },
    {
      id: "monitor-full-hd-24", name: "Monitor Full HD 24”", category: "Computadores",
      price: 649900, previousPrice: 799900, rating: 4.7, reviewCount: 72, stock: 10, sold: 134, age: 11,
      condition: "Como nuevo",
      image: "assets/products/computer-workstation.jpg", alternate: "assets/products/tech-laptop.jpg",
      description: "Monitor LED ideal para estudiar, trabajar o crear una estación de juego. Colores vivos y soporte ajustable para cuidar tu postura.",
      keywords: "monitor pantalla pc computador escritorio gaming oficina",
      features: ["Resolución Full HD 1920 × 1080", "Panel IPS de 24 pulgadas", "Entrada HDMI", "Modo de luz azul baja"],
      variants: { color: ["Negro"] }, featured: true,
    },
    {
      id: "teclado-mecanico-rgb", name: "Teclado mecánico RGB", category: "Computadores",
      price: 219900, previousPrice: 269900, rating: 4.5, reviewCount: 57, stock: 19, sold: 178, age: 5,
      image: "assets/products/computer-gaming.jpg", alternate: "assets/products/games-console.jpg",
      description: "Teclado mecánico compacto con switches precisos y retroiluminación RGB personalizable. Conexión USB plug and play.",
      keywords: "teclado mecanico gamer pc rgb computador accesorios",
      features: ["Switches mecánicos azules", "Iluminación RGB", "Distribución en español", "Cable USB reforzado"],
      variants: { color: ["Negro RGB", "Blanco RGB"] }, bestSeller: true,
    },
    {
      id: "control-inalambrico", name: "Control inalámbrico Bluetooth", category: "Videojuegos",
      price: 199900, previousPrice: 259900, rating: 4.8, reviewCount: 112, stock: 21, sold: 391, age: 4,
      image: "assets/products/games-console.jpg", alternate: "assets/products/games-headset.jpg",
      description: "Control ergonómico con vibración, gatillos sensibles y batería recargable. Compatible con PC, Android y varias consolas.",
      keywords: "control mando videojuego gaming gamepad consola bluetooth",
      features: ["Conexión inalámbrica estable", "Batería recargable USB-C", "Vibración dual", "Compatible con PC y Android"],
      variants: { color: ["Negro", "Blanco", "Azul"] }, featured: true, bestSeller: true,
    },
    {
      id: "consola-portatil-oled", name: "Consola portátil OLED", category: "Videojuegos",
      price: 1349900, previousPrice: 1599900, rating: 4.9, reviewCount: 165, stock: 6, sold: 256, age: 2,
      image: "assets/products/games-headset.jpg", alternate: "assets/products/computer-gaming.jpg",
      description: "Consola portátil con pantalla OLED de alto contraste. Ideal para jugar en casa o llevar tus títulos favoritos a cualquier lugar.",
      keywords: "consola videojuegos portátil gaming oled juegos",
      features: ["Pantalla OLED de 7 pulgadas", "64 GB de almacenamiento", "Mandos desmontables", "Incluye estuche protector"],
      variants: { color: ["Blanco", "Neón"] }, featured: true, isNew: true,
    },
    {
      id: "buzo-oversize-algodon", name: "Buzo oversize de algodón", category: "Ropa",
      price: 119900, previousPrice: 149900, rating: 4.6, reviewCount: 64, stock: 32, sold: 143, age: 6,
      image: "assets/products/clothing-style.jpg", alternate: "assets/products/clothing-jacket.jpg",
      description: "Buzo suave de corte relajado para todos los días. Hecho en algodón de tacto cómodo y con acabados resistentes.",
      keywords: "buzo ropa sudadera oversize algodón moda unisex",
      features: ["Algodón suave", "Corte oversize unisex", "Bolsillo frontal", "Lavable en máquina"],
      variants: { size: ["XS", "S", "M", "L", "XL"], color: ["Arena", "Negro", "Verde oliva"] }, featured: true, isNew: true,
    },
    {
      id: "chaqueta-denim-clasica", name: "Chaqueta denim clásica", category: "Ropa",
      price: 189900, previousPrice: 0, rating: 4.7, reviewCount: 42, stock: 15, sold: 89, age: 12,
      image: "assets/products/clothing-jacket.jpg", alternate: "assets/products/clothing-style.jpg",
      description: "Chaqueta de denim azul con un corte clásico fácil de combinar. Una prenda cómoda para usar durante todo el año.",
      keywords: "chaqueta denim jean ropa moda mujer hombre",
      features: ["Denim de algodón", "Dos bolsillos frontales", "Botones metálicos", "Corte regular"],
      variants: { size: ["S", "M", "L", "XL"], color: ["Azul claro", "Azul oscuro"] }, bestSeller: true,
    },
    {
      id: "tenis-running-urban", name: "Tenis deportivos Urban Run", category: "Calzado",
      price: 219900, previousPrice: 279900, rating: 4.8, reviewCount: 105, stock: 27, sold: 334, age: 3,
      image: "assets/products/shoes-sneaker.jpg", alternate: "assets/products/shoes-boot.jpg",
      description: "Tenis livianos con suela flexible y amortiguación para caminar, correr o completar un look urbano.",
      keywords: "tenis zapatillas zapatos deporte running calzado correr",
      features: ["Suela de caucho antideslizante", "Plantilla acolchada", "Malla transpirable", "Livianos para uso diario"],
      variants: { size: ["36", "37", "38", "39", "40", "41", "42"], color: ["Rojo", "Negro", "Blanco"] },
      featured: true, bestSeller: true,
    },
    {
      id: "botas-cuero-casual", name: "Botas casuales de cuero", category: "Calzado",
      price: 289900, previousPrice: 0, rating: 4.5, reviewCount: 38, stock: 9, sold: 57, age: 15,
      image: "assets/products/shoes-boot.jpg", alternate: "assets/products/shoes-sneaker.jpg",
      description: "Botas de estilo casual con interior acolchado y suela firme. Un básico versátil para la ciudad.",
      keywords: "botas cuero calzado zapatos casual moda",
      features: ["Exterior resistente", "Plantilla cómoda", "Suela con buen agarre", "Cierre lateral"],
      variants: { size: ["37", "38", "39", "40", "41", "42"], color: ["Café", "Negro"] },
    },
    {
      id: "reloj-minimalista", name: "Reloj minimalista de acero", category: "Accesorios",
      price: 159900, previousPrice: 219900, rating: 4.7, reviewCount: 83, stock: 18, sold: 201, age: 7,
      image: "assets/products/accessories-watch.jpg", alternate: "assets/products/accessories-backpack.jpg",
      description: "Reloj de diseño limpio, caja metálica y correa ajustable. Un detalle elegante para completar cualquier estilo.",
      keywords: "reloj accesorio acero elegante pulso moda",
      features: ["Movimiento de cuarzo", "Resistente a salpicaduras", "Correa ajustable", "Garantía de 6 meses"],
      variants: { color: ["Plateado", "Dorado", "Negro"] }, featured: true,
    },
    {
      id: "morral-urbano-20l", name: "Morral urbano impermeable 20 L", category: "Accesorios",
      price: 139900, previousPrice: 0, rating: 4.6, reviewCount: 51, stock: 22, sold: 118, age: 9,
      image: "assets/products/accessories-backpack.jpg", alternate: "assets/products/accessories-watch.jpg",
      description: "Morral liviano con compartimento acolchado para portátil, bolsillos organizadores y tela resistente al agua.",
      keywords: "morral mochila bolso impermeable portátil accesorio",
      features: ["Capacidad de 20 litros", "Compartimento para portátil de 15 pulgadas", "Tela repelente al agua", "Espalda acolchada"],
      variants: { color: ["Negro", "Gris", "Azul"] }, bestSeller: true,
    },
    {
      id: "sofa-modular-lino", name: "Sofá modular de lino beige", category: "Hogar",
      price: 1450000, previousPrice: 1799000, rating: 4.8, reviewCount: 74, stock: 3, sold: 43, age: 14,
      condition: "Usado",
      image: "assets/products/home-sofa.jpg", alternate: "assets/products/home-lamp.jpg",
      description: "Sofá modular de tres puestos, cómodo y en excelente estado. Tela fácil de limpiar y estructura de madera resistente.",
      keywords: "sofa sala muebles hogar sillon lino",
      features: ["Tres puestos amplios", "Tapizado de lino", "Estructura de madera", "Entrega en Bogotá"],
      variants: { color: ["Beige", "Gris humo"] }, featured: true, isNew: true,
    },
    {
      id: "lampara-ceramica", name: "Lámpara de mesa de cerámica", category: "Hogar",
      price: 180000, previousPrice: 225000, rating: 4.7, reviewCount: 31, stock: 12, sold: 77, age: 1,
      image: "assets/products/home-lamp.jpg", alternate: "assets/products/home-sofa.jpg",
      description: "Lámpara artesanal con pantalla de lino y base de cerámica. Una pieza cálida para darle personalidad a tu espacio.",
      keywords: "lampara luz iluminacion decoracion mesa hogar",
      features: ["Base de cerámica esmaltada", "Pantalla de lino", "Compatible con bombillo E27", "Cable con interruptor"],
      variants: { color: ["Marfil", "Terracota"] }, isNew: true,
    },
    {
      id: "mancuernas-ajustables", name: "Set de mancuernas ajustables", category: "Deportes",
      price: 249900, previousPrice: 329900, rating: 4.6, reviewCount: 69, stock: 16, sold: 156, age: 5,
      image: "assets/products/sports-gym.jpg", alternate: "assets/products/sports-ball.jpg",
      description: "Set compacto para entrenar en casa con distintos niveles de peso. Incluye barras, discos y seguros.",
      keywords: "mancuernas pesas gimnasio fitness entrenamiento deporte",
      features: ["Peso ajustable por disco", "Barras antideslizantes", "Incluye estuche", "Ideal para entrenar en casa"],
      variants: { color: ["Negro"] }, featured: true, bestSeller: true,
    },
    {
      id: "balon-futbol-pro", name: "Balón de fútbol Pro", category: "Deportes",
      price: 99900, previousPrice: 129900, rating: 4.8, reviewCount: 92, stock: 34, sold: 286, age: 2,
      image: "assets/products/sports-ball.jpg", alternate: "assets/products/sports-gym.jpg",
      description: "Balón resistente con buen control y rebote uniforme. Perfecto para entrenamientos y partidos entre amigos.",
      keywords: "balon futbol deporte entrenamiento cancha soccer",
      features: ["Talla 5 reglamentaria", "Cubierta resistente", "Cámara de butilo", "Uso en césped natural"],
      variants: { color: ["Blanco/azul", "Blanco/naranja"] }, bestSeller: true, isNew: true,
    },
    {
      id: "kit-rutina-facial", name: "Kit de rutina facial hidratante", category: "Belleza",
      price: 139900, previousPrice: 179900, rating: 4.9, reviewCount: 137, stock: 20, sold: 416, age: 4,
      image: "assets/products/beauty-skincare.jpg", alternate: "assets/products/beauty-makeup.jpg",
      description: "Kit de cuidado facial con limpiador, sérum hidratante y crema. Fórmulas suaves para acompañar tu rutina diaria.",
      keywords: "skincare belleza rostro crema facial serum hidratante",
      features: ["Rutina de tres pasos", "Fórmulas dermatológicamente probadas", "Apto para piel normal y seca", "Sin pruebas en animales"],
      variants: { size: ["Kit 3 productos"] }, featured: true, bestSeller: true,
    },
    {
      id: "set-maquillaje-esencial", name: "Set de maquillaje esencial", category: "Belleza",
      price: 99900, previousPrice: 0, rating: 4.5, reviewCount: 46, stock: 11, sold: 94, age: 18,
      image: "assets/products/beauty-makeup.jpg", alternate: "assets/products/beauty-skincare.jpg",
      description: "Set de maquillaje con tonos fáciles de combinar, ideal para llevar en el bolso o regalar.",
      keywords: "maquillaje belleza cosmeticos sombras labial",
      features: ["Paleta de tonos neutros", "Incluye brocha doble", "Empaque compacto", "Fácil de difuminar"],
      variants: { color: ["Neutros cálidos", "Neutros fríos"] },
    },
    {
      id: "novela-ciudad-bajo-lluvia", name: "La ciudad bajo la lluvia · novela", category: "Libros",
      price: 48000, previousPrice: 59000, rating: 4.8, reviewCount: 214, stock: 28, sold: 721, age: 3,
      image: "assets/products/books-stack.jpg", alternate: "assets/products/books-reading.jpg",
      description: "Una novela cautivadora sobre nuevos comienzos, amistades inesperadas y los secretos que guarda una ciudad.",
      keywords: "libro novela lectura literatura ficcion historia",
      features: ["Edición de tapa blanda", "320 páginas", "Idioma español", "Incluye guía de lectura"],
      variants: { format: ["Tapa blanda", "E-book demo"] }, featured: true, bestSeller: true, isNew: true,
    },
    {
      id: "pack-libros-crecimiento", name: "Pack de 3 libros de crecimiento personal", category: "Libros",
      price: 75000, previousPrice: 0, rating: 4.7, reviewCount: 58, stock: 17, sold: 133, age: 10,
      condition: "Usado",
      image: "assets/products/books-reading.jpg", alternate: "assets/products/books-stack.jpg",
      description: "Tres títulos para explorar nuevos hábitos, creatividad y bienestar. Una selección ideal para regalar o empezar a leer.",
      keywords: "libros lectura habitos creatividad desarrollo personal regalo",
      features: ["Incluye tres títulos", "Tapa blanda", "Edición en español", "En buen estado"],
      variants: {},
    },
    {
      id: "alimento-perro-premium", name: "Alimento premium para perro · 3 kg", category: "Productos para mascotas",
      price: 89900, previousPrice: 109900, rating: 4.9, reviewCount: 163, stock: 25, sold: 542, age: 1,
      image: "assets/products/pets-food.jpg", alternate: "assets/products/pets-dog.jpg",
      description: "Alimento completo para perros adultos con proteína de calidad, vitaminas y minerales para apoyar una vida activa.",
      keywords: "perro mascota alimento comida concentrado croquetas",
      features: ["Bolsa resellable de 3 kg", "Para perros adultos", "Con proteína de pollo", "Envío local disponible"],
      variants: { size: ["3 kg", "8 kg"] }, bestSeller: true, isNew: true,
    },
    {
      id: "cama-mascota-suave", name: "Cama acolchada para mascota", category: "Productos para mascotas",
      price: 109900, previousPrice: 139900, rating: 4.6, reviewCount: 49, stock: 0, sold: 61, age: 20,
      image: "assets/products/pets-dog.jpg", alternate: "assets/products/pets-food.jpg",
      description: "Cama mullida con funda removible y base antideslizante. Ideal para que tu mascota descanse cómodamente.",
      keywords: "cama perro gato mascota descanso hogar",
      features: ["Funda lavable", "Base antideslizante", "Relleno suave", "Tamaño mediano"],
      variants: { size: ["S", "M", "L"], color: ["Gris", "Azul"] },
    },
  ];

  const distribution = [
    { stars: 5, percent: 76 },
    { stars: 4, percent: 17 },
    { stars: 3, percent: 5 },
    { stars: 2, percent: 1 },
    { stars: 1, percent: 1 },
  ];

  window.PRODUCTS = entries.map((entry, index) => {
    const discount = entry.previousPrice
      ? Math.round((1 - entry.price / entry.previousPrice) * 100)
      : 0;
    return {
      ...entry,
      condition: entry.condition || "Nuevo",
      discount,
      available: entry.stock > 0,
      gallery: [entry.image, entry.alternate].filter(Boolean),
      ratingDistribution: distribution,
      reviews: [0, 1, 2].map((offset) => reviews[(index + offset) % reviews.length]),
    };
  });

  window.PRODUCT_CATEGORIES = [
    "Tecnología",
    "Celulares",
    "Computadores",
    "Videojuegos",
    "Ropa",
    "Calzado",
    "Accesorios",
    "Hogar",
    "Deportes",
    "Belleza",
    "Libros",
    "Productos para mascotas",
  ];
})();